apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::640001687359:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-56RWZMfK5GKU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::640001687359:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-28T03:55:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1432"
  uid: 9ed9b4ec-8b92-40bb-aa70-9cbb4ef456db
